config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: %i(create destroy)
  resources :friendships, only: %i(create destroy)
  resources :users, only: :show
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sanbox_api_public_key],
      secret_token: Rails.application.credentials.iex_client[:sanbox_api_secret_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name , last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker)
    where(ticker: ticker).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracker?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracker?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def can_follow?(friend)
    
    !friendships.where(friend_id: friend.id).exists?
  end

  def self.search(param)
    param.strip!
    (matches('first_name',param) + matches('last_name',param) + matches('email',param)).uniq
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id}
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    current_user.friendships.build(friend_id: params[:friend])
    if current_user.save
      flash[:notice] = 'Following user'
    else
      flash[:alert] = 'There was something wrong with the user'
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = 'Stopped following'
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end

    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was succesfully added"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    UserStock.where(user_id: current_user.id, stock_id: stock.id).
      first.destroy
    flash[:notice] = "Stock #{stock.name} was succesfully removed"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
  
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friendships_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Friend was not found'
          format.js { render partial: 'users/friendships_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = 'Please enter a friend name to search'
        format.js { render partial: 'users/friendships_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end%>
<% if alert %>
  <div class="alert alert-danger text-center alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Finance Tracker', root_path, class: 'navbar-brand' %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My portfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'My friends', my_friends_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu">
              <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class='nav-item user-name'>
            <%= icon('fa-solid', 'user')%> <%= current_user.full_name %>
          </li>
          <li class='nav-item'>
            <%= link_to('logout', destroy_user_session_path, class: 'btn btn-danger logout-button btn-xs', method: :delete) %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_friendships_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @friends %>
  <div class="card card-header results-block">
    <% @friends.each do |friend| %>
      <div>
        <strong>Name: </strong> <%= friend.full_name %>
        <strong>Email:  </strong> <%= friend.email%>
        <strong>Actions: </strong> <%= link_to 'view profile', user_path(friend),
        class: 'btn btn-success btn-sm' %>
        <% if current_user.can_follow?(friend) %>
          <%= link_to 'Follow friend',
            friendships_path(friend: friend),
            class: 'btn btn-sm btn-success', method: :post  %>
        <% else %>
          <span class="badge badge-secondary">
            Already following
          </span>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_friendships_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render  'users/friendships_result.html' %>'

app/views/users/_friendships_table.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody >
        <% @friends.each do |friend| %>
          <tr>
            <th scope="row"><%= friend.email %></th>
            <td><%= friend.full_name %></td>
            <td>
              <%= link_to 'View profile', user_path(friend), class: 'btn btn-sm btn-success' %>
              <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-sm btn-warning' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker%>
    <strong>Company name: </strong> <%= @stock.name%>
    <strong>Last price: </strong> <%= @stock.last_price%>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio',
        user_stocks_path(user: current_user, ticker: @stock.ticker ),
        class: 'btn btn-success', method: :post  %>
    <% else %>
      <span class="badge badge-secondary">
        Already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% elsif current_user.stock_already_tracker?(@stock.ticker) %>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render  'users/result.html' %>'

app/views/users/_table.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.can_track_stock?(stock.ticker) %>
                <%= link_to 'Add to portfolio',
                  user_stocks_path(user: current_user, ticker: stock.ticker ),
                  class: 'btn btn-success', method: :post  %>
              <% end %>
              <% if @user == current_user %>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-sm btn-warning' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/friendships.html.erb
<h1>My friendship list</h1>
<hr>
<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: 'Stock ticker symbol', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= icon('fa-solid', 'magnifying-glass', class: 'fa-2x')%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<% if @friends.any? %>
  <%= render 'users/friendships_table' %>
<% end %>

app/views/users/my_friends.html.erb
<h1>My friendship list</h1>
<hr>
<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: 'Stock ticker symbol', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= icon('fa-solid', 'magnifying-glass', class: 'fa-2x')%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<% if @friends.any? %>
  <%= render 'users/friendships_table' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<hr>
<div class="search-area">
  <h3>Search stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true, class: 'form-control form-control-lg' %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= icon('fa-solid', 'magnifying-glass', class: 'fa-2x')%>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<% if @tracked_stocks.any? %>
  <%= render 'users/table' %>
<% end %>

app/views/users/show.html.erb
<h2>user details</h2>
<br><strong>Name: </strong> <%= @user.full_name %>
<br><strong>Email:  </strong> <%= @user.email%>
<br>
<% if current_user.can_follow?(@user) %>
  <%= link_to 'Follow friend',
    friendships_path(friend: @user),
    class: 'btn btn-sm btn-success', method: :post  %>
<% else %>
  <span class="badge badge-secondary">
    Already following
  </span>
<% end %>
<br>
<% if @tracked_stocks.any? %>
  <%= render 'users/table' %>
<% else %>
  <p> This user is not tracking any stock</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to the FinanceTracker app</h1>
<p> Find me in app/views</p>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>